services:
    wearescytale_companies_house.client:
        class: Wearescytale\CompaniesHouseBundle\Service\CompaniesHouseClient
        arguments:
            - '%wearescytale_companies_house.api_key%'
