services:
    wearescytale_companies_house.client:
        class: Wearescytale\CompaniesHouseBundle\Service\CompaniesHouseClient
        arguments:
            - '%wearescytale_companies_house.api_key%'
            - '@wearescytale_companies_house.serializer'

    wearescytale_companies_house.extractor.reflection:
        class: 'Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor'

    wearescytale_companies_house.name_converter.camel_case_to_snake_case:
        class: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'

    wearescytale_companies_house.normalizer.object:
        class: 'Symfony\Component\Serializer\Normalizer\ObjectNormalizer'
        arguments:
            - null
            - '@wearescytale_companies_house.name_converter.camel_case_to_snake_case'
            - null
            - '@wearescytale_companies_house.extractor.reflection'

    wearescytale_companies_house.normalizer.datetime:
        class: 'Wearescytale\CompaniesHouseBundle\Serializer\Normalizer\DateTimeNormalizer'

    wearescytale_companies_house.normalizer.array:
        class: 'Symfony\Component\Serializer\Normalizer\ArrayDenormalizer'

    wearescytale_companies_house.serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            -
                - '@wearescytale_companies_house.normalizer.datetime'
                - '@wearescytale_companies_house.normalizer.array'
                - '@wearescytale_companies_house.normalizer.object'
            -
                - '@serializer.encoder.json'
